/**
 * Offline OpenRouter `/api/v1/models` payload, used by `MockOpenRouterProvider`.
 *
 * Kept inline (not as a JSON file) so the build emits it to `dist/` without
 * an extra copy step. Mix of free, paid, and edge cases so the free
 * detector + snapshot diff exercises every branch.
 */
export const FIXTURE_OPENROUTER_MODELS = {
  data: [
    {
      id: 'meta-llama/llama-3.3-70b-instruct:free',
      name: 'Meta: Llama 3.3 70B Instruct (free)',
      created: 1733527200,
      description: 'Meta\'s Llama 3.3 70B free tier on OpenRouter.',
      context_length: 131072,
      architecture: {
        modality: 'text->text',
        tokenizer: 'Llama3',
        instruct_type: 'llama3',
      },
      pricing: { prompt: '0', completion: '0', request: '0', image: '0' },
      top_provider: { context_length: 131072, max_completion_tokens: 4096, is_moderated: false },
      per_request_limits: { prompt_tokens: '128000', completion_tokens: '4096' },
      supported_parameters: [
        'temperature',
        'top_p',
        'top_k',
        'frequency_penalty',
        'presence_penalty',
        'repetition_penalty',
        'min_p',
        'top_a',
        'seed',
        'max_tokens',
        'response_format',
        'tools',
        'tool_choice',
      ],
    },
    {
      id: 'qwen/qwen-2.5-72b-instruct:free',
      name: 'Qwen 2.5 72B Instruct (free)',
      created: 1726272000,
      description: 'Alibaba\'s Qwen 2.5 72B free tier.',
      context_length: 32768,
      architecture: { modality: 'text->text', tokenizer: 'Qwen', instruct_type: 'qwen2' },
      pricing: { prompt: '0', completion: '0', request: '0', image: '0' },
      top_provider: { context_length: 32768, max_completion_tokens: 4096, is_moderated: false },
      supported_parameters: ['temperature', 'top_p', 'max_tokens', 'response_format', 'tools'],
    },
    {
      id: 'google/gemma-2-9b-it:free',
      name: 'Google Gemma 2 9B (free)',
      created: 1720569600,
      description: 'Gemma 2 9B Instruct free tier.',
      context_length: 8192,
      architecture: { modality: 'text->text', tokenizer: 'Gemma' },
      pricing: { prompt: '0', completion: '0', request: '0', image: '0' },
      top_provider: { context_length: 8192, max_completion_tokens: 2048, is_moderated: false },
      supported_parameters: ['temperature', 'top_p', 'max_tokens'],
    },
    {
      id: 'mistralai/mistral-7b-instruct:free',
      name: 'Mistral 7B Instruct (free)',
      created: 1700524800,
      description: 'Mistral 7B free tier.',
      context_length: 32768,
      architecture: { modality: 'text->text', tokenizer: 'Mistral' },
      pricing: { prompt: '0', completion: '0', request: '0', image: '0' },
      top_provider: { context_length: 32768, max_completion_tokens: 4096, is_moderated: false },
      supported_parameters: ['temperature', 'top_p', 'max_tokens', 'tools'],
    },
    {
      id: 'deepseek/deepseek-chat',
      name: 'DeepSeek Chat',
      created: 1729900800,
      description: 'DeepSeek\'s flagship chat model. Paid.',
      context_length: 65536,
      architecture: { modality: 'text->text', tokenizer: 'DeepSeek' },
      pricing: { prompt: '0.00000014', completion: '0.00000028', request: '0', image: '0' },
      top_provider: { context_length: 65536, max_completion_tokens: 8192, is_moderated: false },
      supported_parameters: ['temperature', 'top_p', 'max_tokens', 'response_format', 'tools'],
    },
    {
      id: 'openai/gpt-4o-mini',
      name: 'OpenAI GPT-4o Mini',
      created: 1721174400,
      description: 'Cheap and fast OpenAI model.',
      context_length: 128000,
      architecture: { modality: 'text+image->text', tokenizer: 'GPT', instruct_type: 'gpt' },
      pricing: { prompt: '0.00000015', completion: '0.0000006', request: '0', image: '0' },
      top_provider: { context_length: 128000, max_completion_tokens: 16384, is_moderated: true },
      supported_parameters: [
        'temperature',
        'top_p',
        'max_tokens',
        'response_format',
        'tools',
        'tool_choice',
        'logprobs',
      ],
    },
    {
      id: 'anthropic/claude-3.5-sonnet',
      name: 'Anthropic Claude 3.5 Sonnet',
      created: 1718841600,
      description: 'Claude 3.5 Sonnet — paid.',
      context_length: 200000,
      architecture: { modality: 'text+image->text', tokenizer: 'Claude' },
      pricing: { prompt: '0.000003', completion: '0.000015', request: '0', image: '0.0048' },
      top_provider: { context_length: 200000, max_completion_tokens: 8192, is_moderated: false },
      supported_parameters: ['temperature', 'top_p', 'max_tokens', 'tools', 'tool_choice', 'top_k'],
    },
    {
      id: 'openrouter/free',
      name: 'OpenRouter Free Router',
      created: 1728345600,
      description: 'Aggregator route — pick the best currently-free model.',
      context_length: 0,
      architecture: { modality: 'text->text' },
      pricing: { prompt: '0', completion: '0', request: '0', image: '0' },
      top_provider: { context_length: 0, is_moderated: false },
      supported_parameters: ['temperature', 'top_p', 'max_tokens'],
    },
    {
      id: 'edge/no-pricing-test',
      name: 'Edge: missing pricing block',
      created: 1735000000,
      description: 'Edge case used to test the free-detector unknown branch.',
      context_length: 16384,
      architecture: { modality: 'text->text' },
      top_provider: { context_length: 16384, is_moderated: false },
      supported_parameters: ['temperature'],
    },
    {
      id: 'edge/partial-zero:free',
      name: 'Edge: prompt free but completion missing',
      created: 1736000000,
      description: 'Edge case used to test the partial-zero free branch.',
      context_length: 4096,
      architecture: { modality: 'text->text' },
      pricing: { prompt: '0' },
      top_provider: { context_length: 4096 },
      supported_parameters: ['temperature', 'max_tokens'],
    },
  ],
} as const;

export const FIXTURE_OPENROUTER_KEY_RESPONSE = {
  data: {
    label: 'fixture-key',
    usage: 0.12345,
    limit: null,
    limit_remaining: null,
    is_free_tier: true,
    rate_limit: { requests: 60, interval: '60s' },
  },
} as const;
